FROM nginx
COPY ./soft_landing /usr/share/nginx/html

# PS D:\GITRepos\Docker\YEAR2023\TRAINING2023-Feb15-00> docker build -t my_nginx_website_image .
# PS D:\GITRepos\Docker\YEAR2023\TRAINING2023-Feb15-00> docker run -d -p 8080:80 my_nginx_website_image
# http://localhost:8080/